# Generated by Django 3.0.7 on 2020-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200623_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
